language: java

jdk:
- openjdk11

os:
  - linux

cache:
  directories:
  - $HOME/.gradle

env:
  - NODE_VERSION=10.16

before_install:
- sudo apt-get -y install libsecret-1-dev

install:
  - nvm install $NODE_VERSION
  - npm install
  - |
    export DISPLAY=':99.0'
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - nvm use $NODE_VERSION
  - | 
    if [[ $TRAVIS_TAG =~ ^v.* ]]; then
      ./gradlew clean final publish publishToOpenVSX -Prelease.useLastTag=true
    else
      ./gradlew clean snapshot vscodeExtension
    fi

