name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore: 
      - 'v*'
  pull_request:

jobs:
  build:
    if: contains(github.event.head_commit.message, 'Release v') == false
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Setup Node
      uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: 18.17
    - name: Install Dependencies
      run: sudo apt-get -y install libsecret-1-dev
    - name: Gradle caches  
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: NPM install
      run: |
        npm install -g npm
        export DISPLAY=':99.0'
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      uses: GabrielBB/xvfb-action@v1.5
      with:
        run: ./gradlew clean snapshot vscodeExtension
      env:
        MS_MARKETPLACE_ACCESS_TOKEN: ${{ secrets.MS_MARKETPLACE_ACCESS_TOKEN }}
        OPENVSX_ACCESS_TOKEN: ${{ secrets.OPENVSX_ACCESS_TOKEN }}
